AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket and DynamoDB table for Terraform state and locks

Parameters:
  Project:
    Type: String
  Env:
    Type: String

# The intrinsic function !Sub substitutes variables in an input string with values that you specify.
# In your templates, you can use this function to construct commands or outputs that,
# include values that aren't available until you create or update a stack.
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html
Resources:
  TerraformS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Project}-terraform-${Env}"
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled

  TerraformDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Project}-terraform-${Env}"
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
